'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowDownToLine,ArrowLeft,ArrowRight,Check,ChevronDown,CircleHelp,Clapperboard,Clock3,Download,ExternalLink,Film,FolderOpen,KeyRound,LayoutGrid,Link2,LoaderCircle,Pause,Play,Plus,Radio,RotateCcw,Scissors,Settings2,ShieldCheck,Smartphone,Square,Subtitles,Video,Wifi,WifiOff,X} from 'lucide-react';
import VideoPlayer from '../components/VideoPlayer';

type Session={id:string,source_url:string,status:string,started_at:string,ended_at:string|null,duration_seconds:number,segments?:number,full_ready?:boolean,error?:string|null};
type Clip={id:string,session_id:string,start_seconds:number,end_seconds:number,title:string,status:string,vertical:number,error?:string|null};
type Export={id:string,clip_id:string,status:string,error?:string|null};
type Caption={start:number,end:number,text:string};
const API=(process.env.NEXT_PUBLIC_CORE_URL||'http://localhost:8000').replace(/\/$/,'');
const time=(seconds:number)=>{if(!Number.isFinite(seconds))return '—';const n=Math.max(0,Math.floor(seconds));return [Math.floor(n/3600),Math.floor(n%3600/60),n%60].map(x=>String(x).padStart(2,'0')).join(':');};
const stamp=(x:string)=>new Date(x).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});

export default function Studio(){
 const [token,setToken]=useState('');
 const [tokenInput,setTokenInput]=useState('');
 const [url,setUrl]=useState('');
 const [tab,setTab]=useState<'monitor'|'recordings'|'library'>('monitor');
 const [session,setSession]=useState<Session|null>(null);
 const [sessions,setSessions]=useState<Session[]>([]);
 const [clips,setClips]=useState<Clip[]>([]);
 const [exports,setExports]=useState<Export[]>([]);
 const [previewTime,setPreviewTime]=useState(0);
 const [markIn,setMarkIn]=useState<number|null>(null);
 const [markOut,setMarkOut]=useState<number|null>(null);
 const [vertical,setVertical]=useState(true);
 const [selectedClip,setSelectedClip]=useState<Clip|null>(null);
 const [editText,setEditText]=useState('');
 const [captions,setCaptions]=useState<Caption[]>([]);
 const [trimStart,setTrimStart]=useState(0);
 const [trimEnd,setTrimEnd]=useState(0);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [notice,setNotice]=useState('');
 const player=useRef<HTMLVideoElement|null>(null);
 const [hlsRevision,setHlsRevision]=useState(0);
 const [clipTitle,setClipTitle]=useState('New highlight');
 useEffect(()=>{const stored=localStorage.getItem('liveclip_key');if(stored){setToken(stored);setTokenInput(stored)}},[]);
 const call=useCallback(async <T,>(path:string,opts:RequestInit={}):Promise<T>=>{
  const res=await fetch(API+path,{...opts,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json',...opts.headers},cache:'no-store'});
  let body:any;try{body=await res.json()}catch{body={detail:'Unreachable API / invalid response'}}
  if(!res.ok)throw new Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail));
  return body as T;
 },[token]);
 const refresh=useCallback(async()=>{
  if(!token)return;
  try{
   const [ss,cc,ee]=await Promise.all([call<Session[]>('/sessions'),call<Clip[]>('/clips'),call<Export[]>('/exports')]);
   setSessions(ss);setClips(cc);setExports(ee);
   setSession(old=>old?(ss.find(s=>s.id===old.id)||old):ss.find(s=>['starting','recording','stopping','finalizing'].includes(s.status))||null);
   setError('');
  }catch(e){setError((e as Error).message)}
 },[call,token]);
 useEffect(()=>{refresh();const id=setInterval(refresh,2500);return()=>clearInterval(id)},[refresh]);
 const start=async()=>{setBusy(true);setError('');try{const row=await call<{id:string}>('/sessions',{method:'POST',body:JSON.stringify({url:url.trim()})});setSession({id:row.id,source_url:url,status:'starting',started_at:new Date().toISOString(),ended_at:null,duration_seconds:0});setTab('monitor');setNotice('Recording started on server');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const stop=async()=>{if(!session)return;setBusy(true);try{await call(`/sessions/${session.id}/stop`,{method:'POST'});setNotice('Stopping recorder; finalizing full MP4');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const makeClip=async()=>{if(!session||markIn===null||markOut===null)return;setBusy(true);try{await call(`/sessions/${session.id}/clips`,{method:'POST',body:JSON.stringify({start_seconds:markIn,end_seconds:markOut,vertical,title:clipTitle})});setNotice('Clip queued. LIVE recording continues.');setMarkIn(null);setMarkOut(null);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const saveDraft=async()=>{if(!selectedClip)return;try{await call(`/clips/${selectedClip.id}/edit`,{method:'PUT',body:JSON.stringify({data:{captions,trimStart,trimEnd,vertical}})});setNotice('Draft saved')}catch(e){setError((e as Error).message)}};
 const openEditor=async(clip:Clip)=>{setSelectedClip(clip);setTrimStart(0);setTrimEnd(clip.end_seconds-clip.start_seconds);setCaptions([]);setEditText('');setVertical(Boolean(clip.vertical));try{const obj=await call<{data:{captions?:Caption[],trimStart?:number,trimEnd?:number,vertical?:boolean}}>(`/clips/${clip.id}/edit`);if(obj.data){setCaptions(obj.data.captions||[]);setTrimStart(obj.data.trimStart??0);setTrimEnd(obj.data.trimEnd??clip.end_seconds-clip.start_seconds);setVertical(obj.data.vertical??Boolean(clip.vertical))}}catch{}setError('')};
 const exportClip=async()=>{if(!selectedClip)return;setBusy(true);try{await call(`/clips/${selectedClip.id}/export`,{method:'POST',body:JSON.stringify({trim_start:trimStart,trim_end:trimEnd,vertical,captions})});setNotice('Export queued. You can open Library from another device.');setTab('library');setSelectedClip(null);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const addCaption=()=>{if(!editText.trim())return;setCaptions([...captions,{start:0,end:Math.min(3,Math.max(0.1,trimEnd-trimStart)),text:editText.trim()}]);setEditText('')};
 const isRecording=!!session&&['starting','recording','stopping','finalizing'].includes(session.status);
 const canClip=markIn!==null&&markOut!==null&&markOut>markIn&&markOut-markIn<=600&&markOut<(session?.duration_seconds||0)-0.05;
 const clipDuration=selectedClip?selectedClip.end_seconds-selectedClip.start_seconds:0;
 const mediaUrl=session?API+`/media/sessions/${session.id}/`+(session.full_ready?'full.mp4':'index.m3u8'):'';
 const seek=(n:number)=>{if(player.current)player.current.currentTime=Math.max(0,n);setPreviewTime(n)};
 const chooseSession=(s:Session)=>{setSession(s);setHlsRevision(p=>p+1);setMarkIn(null);setMarkOut(null);setPreviewTime(0);setTab('monitor')};
 return <div className="shell">
  <header className="topbar"><div className="brand"><div className="brand-icon"><Clapperboard size={20}/></div><span>LiveClip<span className="brand-faint"> Studio</span></span><span className="tag-mini">POC</span></div><div className="header-right"><span className="desktop-note"><ShieldCheck size={14}/> Private workspace</span><span className="avatar">LC</span></div></header>
  <div className="app">
   <nav className="sidebar"><div className="nav-title">WORKSPACE</div><button className={tab==='monitor'?'nav-item active':'nav-item'} onClick={()=>{setTab('monitor');setSelectedClip(null)}}><Radio size={18}/> <span>Live monitor</span></button><button className={tab==='recordings'?'nav-item active':'nav-item'} onClick={()=>{setTab('recordings');setSelectedClip(null)}}><FolderOpen size={18}/> <span>Recordings</span><b>{sessions.length||''}</b></button><button className={tab==='library'?'nav-item active':'nav-item'} onClick={()=>{setTab('library');setSelectedClip(null)}}><Film size={18}/> <span>Video library</span><b>{exports.filter(x=>x.status==='ready').length||''}</b></button><div className="sidebar-bottom"><div className="online-dot"/> Recorder-first workflow<br/><small>Powered by FFmpeg</small></div></nav>
   <main className="content">
    {!token && <div className="dialog-backdrop"><form className="login" onSubmit={e=>{e.preventDefault();const t=tokenInput.trim();localStorage.setItem('liveclip_key',t);setToken(t)}}><div className="brand-icon big"><KeyRound size={22}/></div><h2>Unlock your workspace</h2><p>Enter the private access token configured on the recorder service.</p><input type="password" required placeholder="Access token" value={tokenInput} onChange={e=>setTokenInput(e.target.value)}/><button className="primary" type="submit">Open LiveClip <ArrowRight size={16}/></button><small>This prototype stores your token in this browser.</small></form></div>}
    {error&&<div className="alert"><WifiOff size={16}/>{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
    {notice&&<div className="success"><Check size={16}/>{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    {selectedClip ? <><div className="page-title compact"><button className="iconbtn" onClick={()=>setSelectedClip(null)}><ArrowLeft size={19}/></button><div><h1>Edit clip</h1><p>Trim, reframe, caption, then export an MP4</p></div><div className="page-actions"><button className="secondary" onClick={saveDraft}>Save draft</button><button className="primary" onClick={exportClip} disabled={busy}>Export video <ArrowRight size={16}/></button></div></div><div className="edit-layout"><section className="card editor-video"><div className="player-wrap vertical-preview"><VideoPlayer src={API+`/media/clips/${selectedClip.id}.mp4`}/></div><div className="tool-hint">Source clip · {time(clipDuration)}</div></section><section className="card edit-panel"><h3>Video edit</h3><p className="muted">Adjust final output; recording source is never modified.</p><label>Trim start (seconds)</label><input type="number" min="0" max={Math.max(0,trimEnd-.1)} step="0.1" value={trimStart} onChange={e=>setTrimStart(Number(e.target.value))}/><label>Trim end (seconds)</label><input type="number" min={trimStart+.1} max={clipDuration} step="0.1" value={trimEnd} onChange={e=>setTrimEnd(Number(e.target.value))}/><label className="switchline"><input type="checkbox" checked={vertical} onChange={e=>setVertical(e.target.checked)}/> Vertical TikTok crop · 9:16</label><div className="section-divider"/><h3><Subtitles size={18}/> On-screen captions</h3><p className="muted">Add timed overlay text. Auto-transcription will follow in the next milestone.</p><div className="inline-input"><input placeholder="Your caption…" value={editText} maxLength={200} onChange={e=>setEditText(e.target.value)}/><button className="secondary" onClick={addCaption}><Plus size={16}/></button></div>{captions.map((c,i)=><div className="caption-row" key={i}><input aria-label="Caption start" type="number" step=".1" min="0" value={c.start} onChange={e=>setCaptions(old=>old.map((x,j)=>j===i?{...x,start:Number(e.target.value)}:x))}/><input aria-label="Caption end" type="number" step=".1" min=".1" value={c.end} onChange={e=>setCaptions(old=>old.map((x,j)=>j===i?{...x,end:Number(e.target.value)}:x))}/><input aria-label="Caption text" value={c.text} onChange={e=>setCaptions(old=>old.map((x,j)=>j===i?{...x,text:e.target.value}:x))}/><button className="iconbtn" onClick={()=>setCaptions(old=>old.filter((_,j)=>j!==i))}><X size={15}/></button></div>)}<div className="section-divider"/><button className="primary wide" disabled={busy} onClick={exportClip}><ArrowDownToLine size={18}/> Generate final MP4</button></section></div></> : tab==='monitor' ? <>
     <div className="page-title"><div><div className="eyebrow"><span className="status-dot"/> LIVE WORKSPACE</div><h1>Capture a moment. Keep the whole story.</h1><p>Record broadcasts continuously, rewind the timeline, and create clips instantly.</p></div><div className="page-actions">{isRecording&&<span className="live-badge"><span/> RECORDING</span>}</div></div>
     <div className="sourcebar"><Link2 size={18} className="muted-icon"/><input placeholder="Paste TikTok LIVE link · tiktok.com/@username/live" value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!isRecording)start()}}/><button className="primary" disabled={busy||isRecording||!url.trim()} onClick={start}><Radio size={16}/> Start recording</button></div>
     <div className="workspace-grid"><div className="workspace-left"><section className="card no-pad"><div className="card-heading"><div className="card-heading-title"><Radio size={17} className="red"/><strong>Live player</strong><span className="pill">DVR ENABLED</span></div><span className="muted small">{session?session.status.toUpperCase():'NO SESSION'}</span></div><div className="player-wrap">{session&&session.duration_seconds>0?<VideoPlayer key={session.id+'-'+(session.full_ready?'full':'live')+hlsRevision} src={mediaUrl} live={!session.full_ready} playerRef={player} onTime={setPreviewTime}/>:<div className="empty-player"><div className="live-camera"><Video size={31}/></div><strong>{session?'Connecting to the recording…':'No active broadcast'}</strong><span>{session?'DVR will appear after the first media segment':'Paste a TikTok LIVE URL to begin capturing'}</span></div>}</div><div className="player-footer"><span><span className="indicator"/> {session?session.status:'Waiting for source'}</span><span className="timer">{time(session?.duration_seconds||0)} recorded</span></div></section>
       <section className="card"><div className="section-head"><div><h3>Recording timeline</h3><p>Move the playhead and mark the section you want to keep</p></div><button className="secondary smallbtn" disabled={!session||!session.duration_seconds} onClick={()=>seek(Math.max(0,(session?.duration_seconds||0)-1))}><Radio size={14}/> Go LIVE</button></div><div className="timeline"><div className="timeline-labels"><span>00:00:00</span><span className="timer">{time(previewTime)} / {time(session?.duration_seconds||0)}</span><span>{time(session?.duration_seconds||0)}</span></div><input className="timeline-range" aria-label="Seek timeline" type="range" min={0} max={Math.max(.1,session?.duration_seconds||0)} step=".1" value={Math.min(previewTime,session?.duration_seconds||0)} disabled={!session||!session.duration_seconds} onChange={e=>seek(Number(e.target.value))}/><div className="range-actions"><button className="secondary" disabled={!session?.duration_seconds} onClick={()=>seek(Math.max(0,previewTime-20))}><RotateCcw size={16}/> Back 20s</button><button className="secondary" disabled={!session?.duration_seconds} onClick={()=>setMarkIn(Math.min(previewTime,session?.duration_seconds||0))}>Set IN</button><button className="secondary" disabled={!session?.duration_seconds} onClick={()=>setMarkOut(Math.min(previewTime,session?.duration_seconds||0))}>Set OUT</button></div><div className="range-settings"><div><label>IN POINT</label><input type="number" step="0.1" min="0" value={markIn??''} placeholder="0.0" onChange={e=>setMarkIn(Number(e.target.value))}/></div><span className="dash">→</span><div><label>OUT POINT</label><input type="number" step="0.1" min="0" max={session?.duration_seconds||0} value={markOut??''} placeholder="0.0" onChange={e=>setMarkOut(Number(e.target.value))}/></div><div className="range-length"><label>DURATION</label><strong>{markIn!==null&&markOut!==null?time(Math.max(0,markOut-markIn)):'—'}</strong></div></div></div><div className="create-footer"><label className="switchline"><input type="checkbox" checked={vertical} onChange={e=>setVertical(e.target.checked)}/> 9:16 crop</label><button className="primary" disabled={!canClip||busy} onClick={makeClip}><Scissors size={17}/> Generate clip</button></div></section>
      </div><aside className="workspace-right"><section className="card"><div className="section-head"><h3>Recording status</h3><Activity size={17} className="muted-icon"/></div><div className="metric"><span>Capture state</span><strong className={isRecording?'good':''}>{session?.status||'Idle'}</strong></div><div className="metric"><span>Duration</span><strong className="timer">{time(session?.duration_seconds||0)}</strong></div><div className="metric"><span>Segments</span><strong>{session?.segments??'—'}</strong></div><div className="metric"><span>Source</span><strong className="source-small">{session?.source_url?.split('/@')[1]?.split('/')[0]||'—'}</strong></div><button className="secondary wide dangertext" onClick={stop} disabled={!session||!['recording','starting'].includes(session.status)||busy}><Square size={15}/> Stop and finalize</button></section><section className="card"><div className="section-head"><h3>Recent clips</h3><button className="textbtn" onClick={()=>setTab('library')}>View all <ArrowRight size={14}/></button></div>{clips.filter(c=>!session||c.session_id===session.id).slice(0,4).map(c=><div className="cliprow" key={c.id}><div className="clipthumb"><Scissors size={18}/></div><div className="clipmeta"><strong>{c.title}</strong><span>{time(c.end_seconds-c.start_seconds)} · {c.status}</span></div>{c.status==='ready'&&<button className="iconbtn" title="Edit clip" onClick={()=>openEditor(c)}><ArrowRight size={16}/></button>}</div>)}{!clips.length&&<div className="empty-small"><Scissors size={25}/><p>Your clips will appear here</p></div>}</section><div className="hint"><CircleHelp size={18}/><p><b>Recording stays on the server.</b> Closing this tab will not interrupt an active recording.</p></div></aside></div>
    </> : tab==='recordings'? <><div className="page-title"><div><div className="eyebrow">YOUR ARCHIVE</div><h1>Recordings</h1><p>Every session remains available after the LIVE ends.</p></div></div><div className="card listcard"><div className="listheader"><span>STREAM / SESSION</span><span>RECORDED</span><span>STATUS</span><span></span></div>{sessions.map(s=><div className="listrow" key={s.id}><div className="listidentity"><div className="fileicon"><Radio size={18}/></div><div><strong>{s.source_url.split('/@')[1]?.split('/')[0]||'TikTok LIVE'}</strong><small>{s.id.slice(0,8)} · {stamp(s.started_at)}</small></div></div><span className="timer">{time(s.duration_seconds)}</span><span className={'status-pill '+s.status}>{s.status}</span><button className="secondary" onClick={()=>chooseSession(s)}>Open DVR <ArrowRight size={15}/></button></div>)}{!sessions.length&&<div className="empty-list">No recordings yet. Start a LIVE to create your first session.</div>}</div></> : <><div className="page-title"><div><div className="eyebrow">CREATIVE OUTPUT</div><h1>Video library</h1><p>Ready to edit, preview, and download on any device.</p></div></div><div className="library-grid">{clips.map(c=><div className="card library-card" key={c.id}><div className="library-preview"><Film size={32}/><span>{time(c.end_seconds-c.start_seconds)}</span></div><div className="library-info"><strong>{c.title}</strong><span className={'status-pill '+c.status}>{c.status}</span></div>{c.error&&<p className="error-small">{c.error}</p>}<div className="library-actions"><button className="secondary" disabled={c.status!=='ready'} onClick={()=>openEditor(c)}><Settings2 size={15}/> Edit</button>{c.status==='ready'&&<a className="secondary button-link" href={API+`/media/clips/${c.id}.mp4`} target="_blank" rel="noreferrer"><Download size={15}/> Draft</a>}</div></div>)}{!clips.length&&<div className="empty-list card">No clips created yet. Choose a segment in Live Monitor.</div>}</div><div className="section-head exports-title"><h3>Final exported videos</h3><span className="muted small">Permanent MP4 downloads</span></div><div className="card listcard">{exports.map(x=><div className="listrow exportrow" key={x.id}><div className="listidentity"><div className="fileicon"><Film size={18}/></div><div><strong>Export {x.id.slice(0,8)}</strong><small>{x.status==='ready'?'MP4 ready':'Video rendering job'}</small></div></div><span className={'status-pill '+x.status}>{x.status}</span>{x.error&&<span className="error-small">{x.error}</span>}{x.status==='ready'?<a className="primary button-link" href={API+`/media/exports/${x.id}.mp4`} download><Download size={16}/> Download MP4</a>:<span className="muted small">Processing…</span>}</div>)}{!exports.length&&<div className="empty-list">Exported videos will appear here.</div>}</div></>}
   </main>
  </div>
  <nav className="mobile-nav"><button className={tab==='monitor'?'selected':''} onClick={()=>{setTab('monitor');setSelectedClip(null)}}><Radio size={20}/>LIVE</button><button className={tab==='recordings'?'selected':''} onClick={()=>{setTab('recordings');setSelectedClip(null)}}><FolderOpen size={20}/>Recordings</button><button className={tab==='library'?'selected':''} onClick={()=>{setTab('library');setSelectedClip(null)}}><Film size={20}/>Library</button></nav>
 </div>;
}
